version: '3.8'
services:
  client:
    build: ./app
    restart: always
    container_name: client
    stdin_open: true
    ports:
      - '3000:3000'
    volumes:
      - ./app:/app
      - /app/node_modules
      - /app/.next